import type { Metadata } from 'next'

import '@/styles/globals.css'

import { Geist } from 'next/font/google'
import { Provider } from '../provider';
import DevHelperDock from '@/components/shared/dev-helper-dock';
import { isProduction } from '@/config/constants';
import { cn } from '@/lib/utils';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type RootLayoutProps = Readonly<{
  children: React.ReactNode
}>

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html
      lang="zh-CN"
      className={cn(geistSans.variable, 'scroll-smooth')}
      suppressHydrationWarning
    >
      <body>
        {!isProduction && <DevHelperDock />}
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}

export default RootLayout
